StudentManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views

app_name = 'StudentManagement'
urlpatterns = [

    path('bar/',views.bar),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'), #회원가입
]

info_member/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views

app_name = 'info_member'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('<int:content_id>/', views.detail, name='detail'),
    path('comment/create/<int:content_id>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),

]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("admin/", admin.site.urls),

    path('', include('pages.urls')),

    #path('', include('mysite.urls')),
    path('accounts/', include('accounts.urls')),
    path('StudentManagement/', include('StudentManagement.urls')),
    path('info_member/', include('info_member.urls')),

]

pages/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views

urlpatterns = [
    path('',views.mainpage),
    path('MemberManagement/',views.MemberManagement),
]

StudentManagement/models.py
from django.db import models

# Create your models here.

info_member/models.py
from django.db import models
from django.contrib.auth.models import User

class MainContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published')
# Create your models here.

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(MainContent, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

pages/models.py
from django.db import models


# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=("username","password1","password2","email")

info_member/forms.py
from .models import Comment
from django import forms
class CommentForm(forms.ModelForm):
     class Meta:
         model = Comment
         fields = ('content',)

StudentManagement/views.py
from django.shortcuts import render
from django.shortcuts import render

# Create your views here.
def bar(request):
    return render(request,'StudentManagement/bar.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from accounts.forms import SignupForm

def signup( request ):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form' : form})
# Create your views here.

info_member/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .models import MainContent, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied

# Create your views here.

def index(request):
    content_list = MainContent.objects.order_by('-pub_date')
    context = {'content_list':content_list}
    return render(request,'info_member/info_member.html', context)

def detail(request, content_id):
    content_list=MainContent.objects.get(id=content_id)
    context = {'content_list':content_list}
    return render(request, 'info_member/content_detail.html', context)

def comment_create(request, content_id):
     content_list = get_object_or_404(MainContent, pk=content_id)

     if request.method == 'POST':
         form = CommentForm(request.POST)
         if form.is_valid():
             comment = form.save(commit=False)
             comment.content_list = content_list
             comment.author = request.user
             comment.save()
             return redirect('detail', content_id=content_list.id)
     else:
        form = CommentForm()
     context = {'content_list': content_list, 'form': form}
     return render(request, 'info_member/content_detail.html', context)


@login_required(login_url='accounts:login')
def comment_update(request,comment_id):
    comment=get_object_or_404(Comment,pk=comment_id)

    if request.user!=comment.author:
        raise PermissionDenied

    if request.method=='POST':
        form=CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment=form.save(commeit=False)
            comment.save()
            return redirect('detail', content_id=comment.content_list.id)
    else:
        form=CommentForm(instance=comment)

    context={'comment':comment, 'form':form}
    return render(request, 'info_member/comment_form.html',context)

@login_required(login_url='accounts:login')
def comment_delete(request,comment_id):
    comment=get_object_or_404(Comment,pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    return redirect('detail', content_id=comment.content_list.id)

pages/views.py
from django.shortcuts import render

# Create your views here.
def mainpage(request):
    return render(request,'pages/mainpage.html')

def MemberManagement(request):
    return render(request,'pages/MemberManagement.html')

templates/StudentManagement/MemberManagement.html
{% extends 'min_base.html' %}
{% block content %}
    <div>
    <form method="post" action="member.jsp">
        <select name="search">
            <option value="none">===선택===</option>
            <option value="이름">이름</option>
            <option value="전화번호">전화번호</option>
            <option value="회원번호">회원번호</option>
        </select>
        <input type="text" name="입력값">
        <input type="submit" value="조회하기"><br><br>
    </form>
    </div>
{% endblock %}

templates/StudentManagement/bar.html
{% extends 'base.html' %}

{% block content %}
    <ul>
    <li><a href="/MemberManagement.html/">학생 정보 조회</a></li>
    <li><a href="#">신규 학생 등록</a> </li>
    </ul>
{% endblock %}

templates/StudentManagement/min_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        {% include "bar.html" %}
        {% block content %}
        {% endblock %}

    </body>
</html>

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  {% if form.errors %}
    <p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
  {% endif %}

  <div class="login-container px-2 px-lg-2">
    <form method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}
      <table>
        <tr>
          <td>{{ form.username.label_tag }}</td>
          <td>{{ form.username }}</td>
        </tr>
        <tr>
          <td>{{ form.password.label_tag }}</td>
          <td>{{ form.password }}</td>
        </tr>
      </table>

      <input type="submit" value="로그인">
    </form>
  <a href="{% url 'accounts:signup' %}">signup</a>
  </div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        {% include "navbar.html" %}
        {% block content %}
        {% endblock %}
        {% include "footer.html" %}
    </body>
</html>

templates/footer.html
 <!-- Footer-->
 <footer class="py-5 bg-dark">
     <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">저작권 (주)학습 관리미 2024</p></div>
 </footer>

templates/info_member/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h2>수정</h2>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_update' comment.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3">{{ form.content.value }}</textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/info_member/content_detail.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ content_list.title }}</h2>
<div>
    {{ content_list.content }}
</div>
<section class="mb-5">
     <div class="card bg-light">
         <div class="card-body">
             <form method="post" class="mb-4" action="{% url 'info_member:comment_create' content_list.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3"
            placeholder="내용을 입력해주세요."></textarea>
                 <button type="submit" class="btn btn-primary">등록</button>
             </form>
             {% for comment in content_list.comment_set.all %}
             <div class="d-flex">
                 <div class="ms-3">
                    <div class="fw-bold">{{ comment.author.username }} &nbsp&nbsp
                        {{ comment.create_date }}</div>
                    {{ comment.content }}
                </div>
             </div>
             <br/>
             {% endfor %}
         </div>
     </div>
</section>
{% endblock %}

templates/info_member/info_member.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>info_member</title>
</head>
<body>
<h1>학생 특이사항</h1>
{% if content_list %}
    {% for content in content_list %}
        <hr/>
        <h5><a href="/info_member/{{ content.id }}">{{ content.title }}</a> </h5>
        <!--<h5>{{ content.content }}</h5>-->
    {% endfor %}
{% else %}
    <p>content가 없습니다.</p>
{% endif %}
</body>
</html>
{% endblock %}

templates/navbar.html
 <!-- Responsive navbar-->
 {% load static %}
 <nav class="navbar navbar-expand-lg  navbar-light bg-white">
     <div class="container px-2">
         <div class="d-flex mr-4">
             <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" alt="logo" style="width: 80px; height: auto;"></a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
         </div>

         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                 <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">홈</a></li>
                 <li class="nav-item">
                     <a class="nav-link" href="/StudentManagement/bar/">학생 관리</a>

                 </li>
                 <li class="nav-item"><a class="nav-link" href="/info_member/">근태/학습 관리</a></li>
                 <li class="nav-item"><a class="nav-link" href="#!">상/벌점 관리</a></li>


             </ul>
         </div>
         <div class="d-flex flex-column ml-auto align-items-center">
             <div class="d-flex ml-auto align-items-center">
                 <!--<a class="nav-link text-success align-self-end mb-1" href="/accounts/login/" style="font-size: 14px; text-decoration: underline;">로그인</a>-->
                 <!--화면에서 로그인,로그아웃 여부 확인 가능-->
                 {% if user.is_authenticated %}
                 <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" style="font-size: 14px; text-decoration: underline;">{% csrf_token %} {{ user.username }}(로그아웃)</a></li>
                 {% else %}
                 <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" style="font-size: 14px; text-decoration: underline;">로그인</a> </li>
                 {% endif %}
                 <a class="nav-link text-success align-self-end mb-1" href="/accounts/signup/" style="font-size: 14px; text-decoration: underline;">회원가입</a>
             </div>
             <a class="navbar-brand mb-2"><img src="{% static 'logo2.png' %}" alt="logo" style="width: 200px; height: auto;"></a>

         </div>
     </div>
 </nav>

templates/pages/company_info.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>회원 관리</title>
</head>
<body>
<nav>
    <a href="/company/">company info</a>
    <a href="/mysite/">product</a>
</nav>
{% extends 'base.html' %}
{% block content %}
<h1>회원 관리 페이지입니다. </h1>
{% endblock %}
</body>
</html>

templates/pages/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Content-->
<div class="container px-2 px-lg-2">
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-2">
        <div class="col-lg-12"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'main.png' %}" alt="..." /></div>

    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <p class="text-white m-0">
            <a class="btn btn-success btn-sm rounded" href="#!">관리형이란?</a>
        </p>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">자유 관리석</h2>
                    <p class="card-text">최소한의 관리와 자유를 보장하는 학습 관리 프로그램</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">더 알아보기</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">집중 관리석</h2>
                    <p class="card-text">자제력이 부족한 학생들을 위한 맞춤형 1:1 학습 관리 프로그램</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">더 알아보기</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">성인 전용석</h2>
                    <p class="card-text">공무원/전문직을 준비하는 성인 고객을 위한 맞춤형 관리 프로그램</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">더 알아보기</a></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}